---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(DESeq2)
```
```{r}
df <- read_csv(file = 'data/DE_data_tumor_TP10k.csv')
```

```{r}
df <- column_to_rownames(df, var = "gene") 
head(df)
```
```{r}
sort(rownames(df))
```

```{r}
col_data = read_csv(file = 'data/colData_deseq.csv')
```
```{r}
head(col_data)
```
```{r}
# add 1 so counts are non-zero - deseq gives error if every gene has a 0 value
df = df +1
```
```{r}
head(df)
```
```{r}
for(col in colnames(col_data)){
  if(grepl('zero', col)){
    
    formula = paste('~',col,sept = '')
    dds <- DESeqDataSetFromMatrix(countData=df, 
                                  colData=col_data, 
                                  design=as.formula(formula))
    
    
    dds <- DESeq(dds)
    res <- results(dds)
    
    
    filename = paste('data/deseq_output_',col,'.csv',sep = '')
    write.csv(res, file = filename)
  }

}
```

```{r}



dds <- DESeqDataSetFromMatrix(countData=df, 
                              colData=col_data, 
                              design=as.formula('~HTR1D_zero'))


dds <- DESeq(dds)
res <- results(dds)

```
```{r}

filename = paste('data/deseq_output_',col,'.csv',sep = '')
write.csv(res, file = filename)
```

```{r}


```
```{r}

```

